meta_name: "PROTravellersGuide"
meta_title: "PROTravellersGuide - Unveil the World with a Personal Guide at Your Side"
meta_description: "Local people who can speak or would like to practice speaking in English or curious about different cultures provide “free tours” to foreigners"
meta_image: "banner_small.jpg" # should exist in `app/assets/images/`
twitter_account: "@ToluOlatun97696"   # required for Twitter Cards
